[advisories]
version = 2
yanked = "deny"
ignore = [
 "RUSTSEC-2024-0336", # ignore rustls issue for now until we can upgrade to 0.23
]

[bans]
deny = [
]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "MPL-2.0",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "MIT",
  "Unicode-DFS-2016",
  "LicenseRef-ring",
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
