name: Docker

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update runc
        run: sudo apt-get update && sudo apt-get -y upgrade containerd.io

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 27.0.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.15.1

      - name: Login to Github repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/install-action@just

      - name: Build and push Docker image
        run: >
          just docker-build "--push --tag ghcr.io/${{ github.repository }}:latest --cache-from type=registry,ref=ghcr.io/${{ github.repository }}:buildcache --cache-to type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max --iidfile=$GITHUB_STEP_SUMMARY"
